
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Charly Cimino
 */
public class RegistroAcademico extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroAcademico.class.getName());

    /**
     * Creates new form RegistroAcademico
     */
    public RegistroAcademico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TxtNomnbreCompleto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCarrera = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtPractica = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtParciales = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAsignaciones = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtExamenFinal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtResultado = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro Academico");
        setBackground(new java.awt.Color(102, 255, 255));
        setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnTitulo.setBackground(new java.awt.Color(204, 204, 255));
        pnTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro Academico");
        pnTitulo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 260, 60));

        getContentPane().add(pnTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 110));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel2.setText("Nombre Completo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, 40));

        TxtNomnbreCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNomnbreCompletoActionPerformed(evt);
            }
        });
        jPanel1.add(TxtNomnbreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 150, 40));

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel3.setText("Matricula");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        jPanel1.add(txtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 150, 40));

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel4.setText("Carrera");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 167, 80, 30));
        jPanel1.add(txtCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 150, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 410, 500));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel5.setText("Practica(0-40):");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 130, 40));
        jPanel2.add(txtPractica, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 120, 30));

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel6.setText("Parciales (0-20)");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 150, -1));
        jPanel2.add(txtParciales, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 120, 30));

        jLabel7.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel7.setText("Asignaciones(0-20)");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 30));
        jPanel2.add(txtAsignaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 120, 30));

        jLabel8.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel8.setText("Examen Final (0-20)");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));
        jPanel2.add(txtExamenFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 120, 30));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton1.setText("Calcular Resultado");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, 60));

        txtResultado.setBackground(new java.awt.Color(204, 204, 204));
        txtResultado.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        txtResultado.setPreferredSize(new java.awt.Dimension(320, 170));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setPreferredSize(new java.awt.Dimension(400, 200));
        txtResultado.setViewportView(jTextArea1);

        jPanel2.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 240, 110));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 350, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNomnbreCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNomnbreCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNomnbreCompletoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                                 
    // Validar campos personales
    if (TxtNomnbreCompleto.getText().trim().isEmpty() || 
        txtMatricula.getText().trim().isEmpty() || 
        txtCarrera.getText().trim().isEmpty()) {
        
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Por favor complete todos los datos personales.", 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    try {
        // Obtener calificaciones
        double practicas = Double.parseDouble(txtPractica.getText());
        double parciales = Double.parseDouble(txtParciales.getText());
        double asignaciones = Double.parseDouble(txtAsignaciones.getText());
        double examenFinal = Double.parseDouble(txtExamenFinal.getText());
        
        // Validar rangos
        if (practicas < 0 || practicas > 40) {
            throw new Exception("Las prácticas deben estar entre 0 y 40.");
        }
        if (parciales < 0 || parciales > 20) {
            throw new Exception("Los parciales deben estar entre 0 y 20.");
        }
        if (asignaciones < 0 || asignaciones > 20) {
            throw new Exception("Las asignaciones deben estar entre 0 y 20.");
        }
        if (examenFinal < 0 || examenFinal > 20) {
            throw new Exception("El examen final debe estar entre 0 y 20.");
        }
        
        // Calcular nota total
        double total = practicas + parciales + asignaciones + examenFinal;
        boolean aprobado = total >= 60;
        
        // Crear mensaje de resultado
        StringBuilder resultado = new StringBuilder();
        resultado.append("=== RESULTADO ACADÉMICO ===\n\n");
        resultado.append("Nombre: ").append(TxtNomnbreCompleto.getText()).append("\n");
        resultado.append("Matrícula: ").append(txtMatricula.getText()).append("\n");
        resultado.append("Carrera: ").append(txtCarrera.getText()).append("\n\n");
        resultado.append("Desglose de Calificaciones:\n");
        resultado.append(String.format("  Prácticas:     %.2f/40\n", practicas));
        resultado.append(String.format("  Parciales:     %.2f/20\n", parciales));
        resultado.append(String.format("  Asignaciones:  %.2f/20\n", asignaciones));
        resultado.append(String.format("  Examen Final:  %.2f/20\n", examenFinal));
        resultado.append(String.format("\nNOTA TOTAL:    %.2f/100\n", total));
        resultado.append(String.format("ESTADO:        %s", aprobado ? "APROBADO ✓" : "REPROBADO ✗"));
        
        // Mostrar en el área de texto
        jTextArea1.setText(resultado.toString());
        
        // Cambiar color según resultado
        if (aprobado) {
            jTextArea1.setForeground(new java.awt.Color(0, 128, 0)); // Verde
        } else {
            jTextArea1.setForeground(new java.awt.Color(200, 0, 0)); // Rojo
        }
        
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Por favor ingrese números válidos en las calificaciones.\nNo use letras ni símbolos.", 
            "Error de Formato", 
            JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            e.getMessage(), 
            "Error de Validación", 
            JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistroAcademico().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtNomnbreCompleto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel pnTitulo;
    private javax.swing.JTextField txtAsignaciones;
    private javax.swing.JTextField txtCarrera;
    private javax.swing.JTextField txtExamenFinal;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtParciales;
    private javax.swing.JTextField txtPractica;
    private javax.swing.JScrollPane txtResultado;
    // End of variables declaration//GEN-END:variables
}
