

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Charly Cimino
 */

public class CalculadoraGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName());

    /**
     * Creates new form CalculadoraGUI
     */
    public CalculadoraGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        plValores = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtValor1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtValor2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRespuesta = new javax.swing.JTextField();
        plOperaciones = new javax.swing.JPanel();
        btnSumar = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btnDivicion = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnRaizCuadrada = new javax.swing.JButton();
        btnPotencia = new javax.swing.JButton();
        btnCelsiusAFahrenheit = new javax.swing.JButton();
        btnTemperatura = new javax.swing.JButton();
        txtResultadoCelsius = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        plTitulo.setBackground(new java.awt.Color(102, 102, 102));
        plTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Calculadora Basica");
        plTitulo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, 40));

        getContentPane().add(plTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, -1));

        plValores.setBackground(new java.awt.Color(204, 204, 204));
        plValores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("valor 1:");
        plValores.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        txtValor1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtValor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValor1ActionPerformed(evt);
            }
        });
        txtValor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValor1KeyTyped(evt);
            }
        });
        plValores.add(txtValor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 100, 40));

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Valor 2:");
        plValores.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        txtValor2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtValor2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValor2ActionPerformed(evt);
            }
        });
        txtValor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValor2KeyTyped(evt);
            }
        });
        plValores.add(txtValor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 118, 100, 40));

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Respuesta");
        plValores.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        txtRespuesta.setEditable(false);
        txtRespuesta.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        txtRespuesta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespuestaActionPerformed(evt);
            }
        });
        plValores.add(txtRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 140, 50));

        getContentPane().add(plValores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 290, 310));

        plOperaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSumar.setText("Sumar");
        btnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarActionPerformed(evt);
            }
        });
        plOperaciones.add(btnSumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 40));

        btnResta.setText("Resta");
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });
        plOperaciones.add(btnResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 120, 40));

        btnMultiplicar.setText("Multiplicar");
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });
        plOperaciones.add(btnMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 120, 40));

        btnDivicion.setText("Divicion");
        btnDivicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivicionActionPerformed(evt);
            }
        });
        plOperaciones.add(btnDivicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 120, 40));

        jButton5.setText("Resetear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton5KeyPressed(evt);
            }
        });
        plOperaciones.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 130, 50));

        btnRaizCuadrada.setText("Raiz Cuadreada");
        btnRaizCuadrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaizCuadradaActionPerformed(evt);
            }
        });
        plOperaciones.add(btnRaizCuadrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 120, 40));

        btnPotencia.setText("Potencia");
        btnPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPotenciaActionPerformed(evt);
            }
        });
        plOperaciones.add(btnPotencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 120, 40));

        btnCelsiusAFahrenheit.setText("°C → °F");
        btnCelsiusAFahrenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCelsiusAFahrenheitActionPerformed(evt);
            }
        });
        plOperaciones.add(btnCelsiusAFahrenheit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 90, 30));

        btnTemperatura.setText("°F → °C");
        btnTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemperaturaActionPerformed(evt);
            }
        });
        plOperaciones.add(btnTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 90, 30));
        plOperaciones.add(txtResultadoCelsius, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 242, 100, 40));

        getContentPane().add(plOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 290, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespuestaActionPerformed

    private void txtValor1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValor1KeyTyped
        char numero = evt.getKeyChar();
        if ((numero < '0' || numero > '9') && (numero < ',' || numero > '.')) {
            JOptionPane.showMessageDialog(null, "Favor ingresar numero para realizar la operacion. ");
            evt.consume();

        }
    }//GEN-LAST:event_txtValor1KeyTyped

    private void txtValor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor2ActionPerformed


    }//GEN-LAST:event_txtValor2ActionPerformed

    private void txtValor2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValor2KeyTyped
        char numero = evt.getKeyChar();
        if ((numero < '0' || numero > '9') && (numero < ',' || numero > '.')) {
            JOptionPane.showMessageDialog(null, "Favor ingresar numero para realizar la operacion. ");
            evt.consume();

        }
   
    }//GEN-LAST:event_txtValor2KeyTyped

    private void txtValor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor1ActionPerformed
        
    }//GEN-LAST:event_txtValor1ActionPerformed

    private void jButton5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5KeyPressed

    private void btnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarActionPerformed
                                           
    String t1 = txtValor1.getText();
    String t2 = txtValor2.getText();
    
    if(t1.equals("") || t2.equals("")) {
        JOptionPane.showMessageDialog(this, "Faltan datos");
        return;
    }
    
    try {
        double v1 = Double.parseDouble(t1);
        double v2 = Double.parseDouble(t2);
        txtRespuesta.setText("" + (v1 + v2));
    } catch(Exception e) {
        JOptionPane.showMessageDialog(this, "Solo números por favor");
    }

    }//GEN-LAST:event_btnSumarActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
                                               
    String t1 = txtValor1.getText();
    String t2 = txtValor2.getText();
    
    if(t1.equals("") || t2.equals("")) {
        JOptionPane.showMessageDialog(null, "Faltan datos");
        return;
    }
    
    try {
        double v1 = Double.parseDouble(t1);
        double v2 = Double.parseDouble(t2);
        txtRespuesta.setText("" + (v1 - v2));
    } catch(Exception e) {
        JOptionPane.showMessageDialog(null, "Solo números por favor");
    }

    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
                                               
    String t1 = txtValor1.getText();
    String t2 = txtValor2.getText();
    
    if(t1.equals("") || t2.equals("")) {
        JOptionPane.showMessageDialog(null, "Faltan datos");
        return;
    }
    
    try {
        double v1 = Double.parseDouble(t1);
        double v2 = Double.parseDouble(t2);
        txtRespuesta.setText("" + (v1 * v2));
    } catch(Exception e) {
        JOptionPane.showMessageDialog(null, "Solo números por favor");
    }

    }//GEN-LAST:event_btnMultiplicarActionPerformed

    private void btnDivicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivicionActionPerformed
                                              
    String t1 = txtValor1.getText();
    String t2 = txtValor2.getText();
    
    if(t1.equals("") || t2.equals("")) {
        JOptionPane.showMessageDialog(null, "Faltan datos");
        return;
    }
    
    try {
        double v1 = Double.parseDouble(t1);
        double v2 = Double.parseDouble(t2);
        
        
        if (v2 == 0) {
            JOptionPane.showMessageDialog(null, "Error: No se puede dividir por cero", "Error Matemático", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        txtRespuesta.setText("" + (v1 / v2));
    } catch(Exception e) {
        JOptionPane.showMessageDialog(null, "Solo números por favor");
    }

    }//GEN-LAST:event_btnDivicionActionPerformed

    private void btnRaizCuadradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaizCuadradaActionPerformed
         String t1 = txtValor1.getText();
    
        if(t1.equals("")) {
            JOptionPane.showMessageDialog(null, "Falta el número para la raíz");
            return;
        }
    
        try {
            double v1 = Double.parseDouble(t1);
            
            if (v1 < 0) {
                JOptionPane.showMessageDialog  (null, "Error: No existe raíz de negativo", "Error Matemático", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            txtRespuesta.setText("" + Math.sqrt(v1));
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Solo números por favor");
        }
                
    
    }//GEN-LAST:event_btnRaizCuadradaActionPerformed

    private void btnCelsiusAFahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCelsiusAFahrenheitActionPerformed
        String t1 = txtValor1.getText();
    
        if(t1.equals("")) {
            JOptionPane.showMessageDialog(null, "Falta el número para la raíz");
            return;
        }
    
        try {
            double v1 = Double.parseDouble(t1);
            
            if (v1 < 0) {
                JOptionPane.showMessageDialog(null, "Error: No existe raíz de negativo", "Error Matemático", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            txtRespuesta.setText("" + Math.sqrt(v1));
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Solo números por favor");
        }
                                                                        
    
      

    }//GEN-LAST:event_btnCelsiusAFahrenheitActionPerformed

    private void btnTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemperaturaActionPerformed
     String t1 = txtValor1.getText();
        
        if(t1.equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese la temperatura en Valor 1");
            return;
        }
        
        try {
            double fahrenheit = Double.parseDouble(t1);
            double celsius = (fahrenheit - 32) * 5/9.0;
            txtResultadoCelsius.setText(String.format("%.2f °C", celsius));
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Solo números por favor");
        }
                                                       
   
    }//GEN-LAST:event_btnTemperaturaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        txtValor1.setText("");
        txtValor2.setText("");
        txtRespuesta.setText("");
        txtResultadoCelsius.setText("");
        txtValor1.requestFocus();
                                                                                     

    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPotenciaActionPerformed
         String t1 = txtValor1.getText();
        String t2 = txtValor2.getText();
        
        if(t1.equals("") || t2.equals("")) {
            JOptionPane.showMessageDialog(null, "Faltan datos");
            return;
        }
        
        try {
            double v1 = Double.parseDouble(t1);
            double v2 = Double.parseDouble(t2);
            txtRespuesta.setText("" + Math.pow(v1, v2));
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Solo números por favor");
        }
    
    }//GEN-LAST:event_btnPotenciaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable(){
        public void run(){
     
        new CalculadoraGUI().setVisible(true);
             }
    });
    
}             
         


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCelsiusAFahrenheit;
    private javax.swing.JButton btnDivicion;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnPotencia;
    private javax.swing.JButton btnRaizCuadrada;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSumar;
    private javax.swing.JButton btnTemperatura;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel plOperaciones;
    private javax.swing.JPanel plTitulo;
    private javax.swing.JPanel plValores;
    private javax.swing.JTextField txtRespuesta;
    private javax.swing.JTextField txtResultadoCelsius;
    private javax.swing.JTextField txtValor1;
    private javax.swing.JTextField txtValor2;
    // End of variables declaration//GEN-END:variables
}
